const swaggerUi = require("swagger-ui-express");
const swaggerJsdoc = require("swagger-jsdoc");
const path = require("../env");

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: "NodeJS Basic API",
      version: "1.0.0",
      description: "Test Express API with autogenerated swagger doc"
    },
    basePath: path.basePath,
    schemes: ["http", "https"]
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: [
    "./config/swagger/swaggerConfig.js",
    "./src/routes/*.js",
    "./src/models/*.js"
  ]
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
  //Swagger
  app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
};
